"""initial schema

Revision ID: ec04c378f3f6
Revises: 
Create Date: 2026-09-12 05:40:35.626457
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from app.models import UTCDateTime


revision = 'ec04c378f3f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('owner_org_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_class', sa.String(length=20), nullable=False),
    sa.Column('identity_version', sa.Integer(), nullable=False),
    sa.Column('current_epoch_id', sa.String(length=64), nullable=True),
    sa.Column('a2a_endpoint', sa.String(length=500), nullable=True),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_epoch_id'], ['trust_epochs.epoch_id'], ),
    sa.ForeignKeyConstraint(['owner_org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('audit_events',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity_time', ['entity_type', 'entity_id', 'created_at'], unique=False)

    op.create_table('delegations',
    sa.Column('delegation_id', sa.String(length=64), nullable=False),
    sa.Column('requester_agent_id', sa.String(length=64), nullable=False),
    sa.Column('delegate_agent_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('task_class', sa.String(length=120), nullable=True),
    sa.Column('transaction_value', sa.Float(), nullable=True),
    sa.Column('risk_class', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('decision_detail', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('proposed_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('decided_at', UTCDateTime(), nullable=True),
    sa.Column('closed_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('delegation_id')
    )
    op.create_table('organizations',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('did', sa.String(length=300), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('policy_rules',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('matcher', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('replay_windows',
    sa.Column('nonce', sa.String(length=120), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('seen_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('security_incidents',
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detected_at', UTCDateTime(), nullable=False),
    sa.Column('resolved_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    with op.batch_alter_table('security_incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_kind_time', ['kind', 'detected_at'], unique=False)

    op.create_table('trust_epochs',
    sa.Column('epoch_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('epoch_number', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('ended_at', UTCDateTime(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('continuity', sa.JSON(), nullable=True),
    sa.Column('reputation_baseline', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('epoch_id'),
    sa.UniqueConstraint('agent_id', 'epoch_number', name='uq_epoch_number')
    )
    op.create_table('trust_relationships',
    sa.Column('relationship_id', sa.String(length=64), nullable=False),
    sa.Column('issuer_agent_id', sa.String(length=64), nullable=True),
    sa.Column('issuer_org_id', sa.String(length=64), nullable=True),
    sa.Column('subject_agent_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('evidence_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    with op.batch_alter_table('trust_relationships', schema=None) as batch_op:
        batch_op.create_index('ix_trustrel_subject', ['subject_agent_id'], unique=False)

    op.create_table('agent_versions',
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('identity_version', sa.Integer(), nullable=False),
    sa.Column('epoch_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=200), nullable=True),
    sa.Column('model_family', sa.String(length=100), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['epoch_id'], ['trust_epochs.epoch_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('evidence_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=True),
    sa.Column('task_class', sa.String(length=120), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('issuer_type', sa.String(length=30), nullable=False),
    sa.Column('issuer_id', sa.String(length=120), nullable=False),
    sa.Column('signing_key_id', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=80), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=80), nullable=True),
    sa.Column('event_hash', sa.String(length=80), nullable=False),
    sa.Column('quality_tier', sa.String(length=30), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('corrective_of', sa.String(length=64), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('agent_id', 'seq', name='uq_agent_seq')
    )
    with op.batch_alter_table('evidence_events', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_agent_type_time', ['agent_id', 'event_type', 'created_at'], unique=False)
        batch_op.create_index('ix_evidence_capability_time', ['capability', 'created_at'], unique=False)

    op.create_table('reputation_snapshots',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=False),
    sa.Column('epoch_id', sa.String(length=64), nullable=True),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('computed_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('reputation_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_repsnap_agent_cap_time', ['agent_id', 'capability', 'computed_at'], unique=False)

    op.create_table('signing_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('public_key_b64', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('retired_at', UTCDateTime(), nullable=True),
    sa.Column('revoked_at', UTCDateTime(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('key_id')
    )
    with op.batch_alter_table('signing_keys', schema=None) as batch_op:
        batch_op.create_index('ix_signing_keys_agent_status', ['agent_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signing_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_signing_keys_agent_status')

    op.drop_table('signing_keys')
    with op.batch_alter_table('reputation_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_repsnap_agent_cap_time')

    op.drop_table('reputation_snapshots')
    with op.batch_alter_table('evidence_events', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_capability_time')
        batch_op.drop_index('ix_evidence_agent_type_time')

    op.drop_table('evidence_events')
    op.drop_table('agent_versions')
    with op.batch_alter_table('trust_relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_trustrel_subject')

    op.drop_table('trust_relationships')
    op.drop_table('trust_epochs')
    with op.batch_alter_table('security_incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_kind_time')

    op.drop_table('security_incidents')
    op.drop_table('replay_windows')
    op.drop_table('policy_rules')
    op.drop_table('organizations')
    op.drop_table('delegations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity_time')

    op.drop_table('audit_events')
    op.drop_table('agents')
    # ### end Alembic commands ###
